### PR TITLE
more verbose showdown extension recommendations

### PR DESCRIPTION
**Pull request by kybishop**
This PR doubles as a sanity check as to where showdown extensions should be registered ;)

### CODE REVIEW

**Comment by gcollazo** [comment]
Thanks @kybishop I can't review since I don't have a use for extensions at the moment. Maybe @nikz can take a look.

**Comment by nikz** [comment]
It's similar to what I'm doing:

`showdown-extname.js`:

```js
/* global showdown */

showdown.extension("emoji", function() {

  return [{
    type: "lang",
    regex: "",
    replace: function() {}
  }];

});
```

`component.js`:
```js
import 'myapp/utils/showdown-extname';
```

**Comment by kybishop** [comment]
@nikz but where are you putting `showdown-extname.js`? I do think it would be good to show a concrete showdown extension example, but this PR was more to address where those extensions should be registered.

**Comment by nikz** [comment]
@kybishop I've got it in a `utils` directory - initializer seems like it might be more standard though.

**Comment by kybishop** [comment]
@nikz :+1:

@nikz + @gcollazo all that said, thoughts on a merge?

**Comment by gcollazo** [comment]
thanks @kybishop for the PR and @nikz for the input.

**Pull request merged**
