### PR TITLE
Support showdown options

### PR DESCRIPTION
**Pull request by joshuaclayton**
This branch:

* updates Showdown to 1.2.2
* allows showdown options to be set on the converter prior to processing text

I've included tests exercising three of the showdown options.

### CODE REVIEW

**Comment by joshuaclayton** [comment]
The failing tests look to be related to Ember 2.0...

**Comment by MattMSumner** [comment]
Apart from the failing test this looks like a reasonable change to me.

**Comment by dylanfoster** [comment]
> The failing tests look to be related to Ember 2.0...

It also seems to be unrelated to this pr.

**Comment by gcollazo** [comment]
@joshuaclayton can you please rebase with master, so we can get the tests fixed and merge?

**Comment by dylanfoster** [comment]
@joshuaclayton let me know if you need any help getting this rebased.

**Comment by joshuaclayton** [comment]
@gcollazo rebased and set to go!

**Comment by gcollazo** [comment]
@joshuaclayton one last thing. Can you update the README with some info about the available options?

**Comment by joshuaclayton** [comment]
@gcollazo sure thing - I've included an example and linked to Showdown's README discussing the various options. Let me know if there's anything else I can do to help push this through!

**Comment by gcollazo** [comment]
Thanks for the contrib @joshuaclayton and everyone else.

**Pull request merged**
