### PR TITLE
Only import the jQuery plugin outside of fastboot

### PR DESCRIPTION
**Pull request by Dhaulagiri**

### CODE REVIEW

**Comment by jasonmit** [comment]
Actually, I may revert this because I don't believe showdown has a dependency on jQuery

**Comment by Dhaulagiri** [comment]
FWIW this addon does break fastboot apps, but the problem could be something different

**Comment by Dhaulagiri** [comment]
I don't think I tried that so maybe that is the key

**Comment by jasonmit** [comment]
Okay, I added fastboot support https://github.com/gcollazo/ember-cli-showdown/pull/20

**Pull request merged**
